#!/bin/bash
### BEGIN INIT INFO
# Provides:          ftp-to-smb
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Merging PDF documents
### END INIT INFO

sourceDir=$(dirname $(readlink -f $0))

case "$1" in
start)
   ${sourceDir}/service &
   echo $!>/var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-service.pid
   ;;
stop)
   kill `cat /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-service.pid`
   rm /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-service.pid
   if [ -e /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-getfiles.pid ]; then
     kill `cat /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-getfiles.pid`
     rm /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-getfiles.pid
   fi
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-service.pid ]; then
      echo service is running, pid=`cat /var/run/$(echo ${sourceDir} | sed -e 's/\//-/g')-service.pid`
   else
      echo service is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
