#!/bin/bash
### BEGIN INIT INFO
# Provides:          ftp-to-smb
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Merging PDF documents
### END INIT INFO

sourceDir=$(dirname $(readlink -f $0))

case "$1" in
start)
   ${sourceDir}/service &
   echo $!>${sourceDir}/tmp/service.pid
   ;;
stop)
   kill `cat ${sourceDir}/tmp/service.pid`
   rm ${sourceDir}/tmp/service.pid
   if [ -e ${sourceDir}/tmp/getfiles.pid ]; then
     kill `cat ${sourceDir}/tmp/getfiles.pid`
     rm ${sourceDir}/tmp/getfiles.pid
   fi
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e ${sourceDir}/tmp/service.pid ]; then
      echo service is running, pid=`cat ${sourceDir}/tmp/service.pid`
   else
      echo service is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
